CREATE TABLE CUSTOMER (
    CUSTOMER_ID   VARCHAR2(20) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(20) NOT NULL,
    CUSTOMER_TEL  NUMBER
);

CREATE TABLE PRODUCT (
    PRODUCT_ID   VARCHAR2(20) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(20) NOT NULL,
    PRICE        NUMBER,
    CONSTRAINT CHK_PRODUCT_PRICE_POSITIVE CHECK (PRICE > 0)
);

CREATE TABLE ORDERS (
    CUSTOMER_ID  VARCHAR2(20),
    PRODUCT_ID   VARCHAR2(20),
    QUANTITY     NUMBER,
    TOTAL_AMOUNT NUMBER,
    CONSTRAINT PK_ORDERS PRIMARY KEY (CUSTOMER_ID, PRODUCT_ID),
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_ORDERS_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (PRODUCT_ID)
);

ALTER TABLE PRODUCT
ADD CATEGORY VARCHAR2(20);

ALTER TABLE ORDERS
ADD ORDERDATE DATE DEFAULT SYSDATE;
