-- Insert products
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE)
VALUES ('P01', 'Samsung Galaxy S20', 'Smartphone', 3299);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE)
VALUES ('P02', 'ASUS Notebook', 'PC', 4599);

-- Insert customers
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TEL)
VALUES ('C01', 'ALI', 71321009);

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_TEL)
VALUES ('C02', 'ASMA', 77345823);

-- Insert orders
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, ORDERDATE, QUANTITY, TOTAL_AMOUNT)
VALUES ('C01', 'P02', NULL, 2, 9198);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_ID, ORDERDATE, QUANTITY, TOTAL_AMOUNT)
VALUES ('C02', 'P01', TO_DATE('28/05/2020', 'DD/MM/YYYY'), 1, 3299);

COMMIT;
